# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__commit_id__",
    "__version__",
    "__version_tuple__",
    "commit_id",
    "version",
    "version_tuple",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = "2.5.1.dev1+ga9aea99ee.d20260913"
__version_tuple__ = version_tuple = (2, 5, 1, "dev1", "ga9aea99ee.d20260913")

__commit_id__ = commit_id = "ga9aea99ee"
